version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: edutuition_app
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - JWT_SECRET=super_secret_jwt_key_2025
      - MONGODB_URI=mongodb://mongo:27017/edutuition
    depends_on:
      - mongo
    volumes:
      - app_data:/app/backend/data

  mongo:
    image: mongo:7-jammy
    container_name: edutuition_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
  app_data:
